### ISSUE TITLE
If_Statement KeyError

### ISSUE THREAD

**Issue by davidlibland** [EvanKepner/mutatest#19] opened 2019-11-08 21:29 UTC
Running mutatest on the following project results in a KeyError:

silly_module.py:
```
def do_nothing(x):
    if True:
        pass
    return x
```

test_silly_module.py:
```
from silly_module import do_nothing

def test_do_nothing():
    assert do_nothing(5) == 5
```

We get the following error:
```
2019-11-08 13:27:18,370: Current target location: silly_module.py, LocIndex(ast_class='If', lineno=2, col_offset=4, op_type='If_True')
Traceback (most recent call last):
  File "/miniconda3/envs/mutation_tests/bin/mutatest", line 11, in <module>
    load_entry_point('mutatest', 'console_scripts', 'mutatest')()
  File "/dev/mutatest/mutatest/cli.py", line 684, in cli_main
    main(args)
  File "/dev/mutatest/mutatest/cli.py", line 731, in main
    src_loc=src_loc, test_cmds=args.testcmds, config=config
  File "/dev/mutatest/mutatest/run.py", line 424, in run_mutation_trials
    max_runtime=config.max_runtime,
  File "/dev/mutatest/mutatest/run.py", line 351, in create_mutation_run_trial
    mutant = genome.mutate(target_idx, mutation_op, write_cache=True)
  File "/dev/mutatest/mutatest/api.py", line 329, in mutate
    deepcopy(self.ast)  # deepcopy to avoid in-place modification of AST
  File "/miniconda3/envs/mutation_tests/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/miniconda3/envs/mutation_tests/lib/python3.7/ast.py", line 317, in generic_visit
    value = self.visit(value)
  File "/miniconda3/envs/mutation_tests/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/miniconda3/envs/mutation_tests/lib/python3.7/ast.py", line 317, in generic_visit
    value = self.visit(value)
  File "/miniconda3/envs/mutation_tests/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/dev/mutatest/mutatest/transformers.py", line 272, in visit_If
    ast.If(test=if_mutations[self.mutation], body=node.body, orelse=node.orelse),
KeyError: 'If_Statement'
```

**Comment by EvanKepner** [comment] 2019-11-09 14:25
Interesting, I can't reproduce this though (v1.2.0). When I run `mutatest -s silly_module.py` it will find two surviving mutants:

```
$ mutatest -s silly_module.py 
2019-11-09 09:19:48,246: Running clean trial
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.7.4, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
plugins: cov-2.7.1, forked-1.0.2, xdist-1.29.0, hypothesis-4.37.0
collected 1 item                                                                                                                                                          

test_silly.py .                                                                                                                                                     [100%]

============================================================================ 1 passed in 0.01s ============================================================================
2019-11-09 09:19:48,539: 2 mutation targets found in silly_module.py AST.
2019-11-09 09:19:48,539: Setting random.seed to: None
2019-11-09 09:19:48,540: Coverage file does not exist, proceeding to sample from all targets.
2019-11-09 09:19:48,540: Total sample space size: 2
2019-11-09 09:19:48,540: 10 exceeds sample space, using full sample: 2.
2019-11-09 09:19:48,540: Starting individual mutation trials!
2019-11-09 09:19:48,540: Current target location: silly_module.py, LocIndex(ast_class='If', lineno=2, col_offset=4, op_type='If_True')
2019-11-09 09:19:48,829: Result: Survived at silly_module.py: (2, 4)
2019-11-09 09:19:48,829: Break on survival: stopping further mutations at location.
2019-11-09 09:19:48,829: Current target location: silly_module.py, LocIndex(ast_class='NameConstant', lineno=2, col_offset=7, op_type=True)
2019-11-09 09:19:49,119: Result: Survived at silly_module.py: (2, 7)
2019-11-09 09:19:49,119: Break on survival: stopping further mutations at location.
2019-11-09 09:19:49,119: Running clean trial
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.7.4, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
plugins: cov-2.7.1, forked-1.0.2, xdist-1.29.0, hypothesis-4.37.0
collected 1 item                                                                                                                                                          

test_silly.py .                                                                                                                                                     [100%]

============================================================================ 1 passed in 0.01s ============================================================================
2019-11-09 09:19:49,413: CLI Report:

Mutatest diagnostic summary
===========================
 - Source location: /x/silly_module.py
 - Test commands: ['pytest']
 - Mode: s
 - Excluded files: []
 - N locations input: 10
 - Random seed: None

Random sample details
---------------------
 - Total locations mutated: 2
 - Total locations identified: 2
 - Location sample coverage: 100.00 %


Running time details
--------------------
 - Clean trial 1 run time: 0:00:00.292234
 - Clean trial 2 run time: 0:00:00.293344
 - Mutation trials total run time: 0:00:00.580450

2019-11-09 09:19:49,413: Trial Summary Report:

Overall mutation trial summary
==============================
 - SURVIVED: 2
 - TOTAL RUNS: 2
 - RUN DATETIME: 2019-11-09 09:19:49.413492

2019-11-09 09:19:49,413: Detected mutations:

2019-11-09 09:19:49,413: Timedout mutations:

2019-11-09 09:19:49,413: Surviving mutations:

SURVIVED
--------
 - silly_module.py: (l: 2, c: 4) - mutation from If_True to If_False
 - silly_module.py: (l: 2, c: 7) - mutation from True to False

```

**Comment by EvanKepner** [comment] 2020-01-03 17:20
I'm going to close this since there hasn't been new commentary and I couldn't reproduce it. Happy to have it re-opened if more details become available for troubleshooting.

**Closed by EvanKepner** 2020-01-03 17:20 UTC
